language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: Vk3WVw2sz4mOqTUUWNo2+muHMKtY1Np2az6g+SXGa7DTCTZUx0syAoUw8hVcwvbtm3R28pV+EMr5Q9x8Qg34PdbylD38ceKLFChDDVwPu2zjwLpYw18ZwJAFCUPY73nYbDExe20VzR6AFV4643vCF33uHVQLcJmBBgwJFiAYoAcXTeSygSPzUzu86J4T5hhYDmvBLKtpO7KorXWAStp0+eaW4Gb9kBzMPPishwY1ickYiKhwubPhmJ6hYD8yVWeUiFxXEe1HxNCBjjcF2BpA196aMXeaaN0jIbq/x1WYrJsi6cuy9RirQby1x+hD/Dpzw+aT55yxoFEVtkvsSWhw2o2FK5Mgk48tXFx2+Vqt3rjGK8Y2HUtP5qQImunzjluq0x5Gx8loY7SkytU4gcOEo2fMBetZ5wbCzDEU/46o0jee9mWsSASrbIp1N4S/rVpaogRciyHuOB+TVtuJEGAfd3nyNjV2K7VmwQziZwIP5jENUXdwXa2fvGM+wW9dDETpJagxEKIhHIfU2u0jsYayXtUd09ux3Yp1i0o/TWOsbSYteup5XeyTqX53ACP3vsXHw0zuIMsiAbrkP5GmzbXvbZThwt3fYSDi0ew41ZijADIlKUvaHW7UQd+41YvUsMUFUAdMvHP8qjpvx1wFS4F+2QjvJ+yxj3P+vWju4tYMmWE=
